# Site settings
title: Josh Eaton
description: Josh Eaton's personal site. AWS Python and Ansible enthusiast.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Josh Eaton
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Cloud Engineer
email: josheatonis234@gmail.com
twitter_username: beartime234
github_username:  beartime234
linkedin_username:  josh-eaton

exclude: ['package.json', 'src' , 'node_modules']
