# Site settings
title: Josh Eaton
description: Josh Eaton's personal site. AWS, Python and Security expert.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Josh Eaton
user_description: An expert in Cloud Security and Software engineering in Python.
tech_1: I have 7+ years experience building Cloud based systems. I have professional experience in AWS, Azure and Google Cloud. I have achieved 5 AWS Certifications and a Google Cloud Engineering Certification.
tech_2: I am an expert in Python. I love writing Python code and enjoying learning and improving my knowledge daily. I have also used Go, Rust and Javascript in a professional setting and enjoy building with those platforms.
tech_3: I use a wide variety of tools to support my engineering such as Git, Ansible, Terraform, CDK for automation, infrastructure and version control. 
user_title: Python, Cloud and Security Expert.
email: josheatonis234@gmail.com
twitter_username: beartime234
github_username:  beartime234
linkedin_username:  josh-eaton

exclude: ['package.json', 'src' , 'node_modules', 'LICENSE.txt', "gulpfile.js", "particle.jpg", "README.md", "yarn.lock", "update-site.sh"]
